spring:
    profiles:
        active: dev
    freemarker:
        suffix: .html
jfish: 
    mvc: 
        mediaTypes:
            json: application/json
            xls: application/vnd.ms-excel
            xml: application/xml
siteConfig:
    name: 后台管理系统
    config:
        profile:
            timeit: true
        security:
            preventXssRequest: true